//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatTracker_Angular_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Tees = new HashSet<Tee>();
        }
    
        public int CourseId { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public string Name { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual ICollection<Tee> Tees { get; set; }
    }
}
