//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatTracker_Angular_Mvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GolfStatTrackerEntities : DbContext
    {
        public GolfStatTrackerEntities()
            : base("name=GolfStatTrackerEntities")
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}
    
        public DbSet<Course> Courses { get; set; }
        public DbSet<Facility> Facilities { get; set; }
        public DbSet<Golfer> Golfers { get; set; }
        public DbSet<Hole> Holes { get; set; }
        public DbSet<Round> Rounds { get; set; }
        public DbSet<RoundDetail> RoundDetails { get; set; }
        public DbSet<Tee> Tees { get; set; }
    }
}
