//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatTracker_Angular_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tee
    {
        public Tee()
        {
            this.Holes = new HashSet<Hole>();
            this.Courses = new HashSet<Course>();
        }
    
        public int TeeId { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Slope { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<byte> Yardage { get; set; }
    
        public virtual ICollection<Hole> Holes { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
    }
}
